// lucide-react name → Material Symbols ligature, for the move to <Icon>
// (docs/ui-guideline.md §1.11). Use the ligature directly in new code:
// <Icon name="add" />. This table exists so every page maps the same way.
export const LUCIDE_TO_SYMBOL = {
  AlertCircle: 'error', AlertTriangle: 'warning', ArrowDownRight: 'south_east', ArrowLeft: 'arrow_back',
  ArrowRight: 'arrow_forward', ArrowRightLeft: 'swap_horiz', ArrowUp: 'arrow_upward', ArrowUpRight: 'north_east',
  Ban: 'block', Bell: 'notifications', BellOff: 'notifications_off', BookOpen: 'menu_book', Bookmark: 'bookmark',
  Bot: 'smart_toy', Bug: 'bug_report', Building2: 'domain', Calculator: 'calculate', Calendar: 'calendar_today',
  CalendarDays: 'calendar_month', CalendarRange: 'date_range', CalendarX: 'event_busy', Check: 'check',
  CheckCheck: 'done_all', CheckCircle2: 'check_circle', CheckSquare: 'check_box', ChevronDown: 'expand_more',
  ChevronLeft: 'chevron_left', ChevronRight: 'chevron_right', ChevronUp: 'expand_less',
  ClipboardCheck: 'assignment_turned_in', ClipboardList: 'assignment', Clock: 'schedule', Clock3: 'schedule',
  CloudDownload: 'cloud_download', Copy: 'content_copy', CornerDownRight: 'subdirectory_arrow_right',
  Download: 'download', DownloadCloud: 'cloud_download', ExternalLink: 'open_in_new', Eye: 'visibility',
  EyeOff: 'visibility_off', File: 'draft', FileAudio: 'audio_file', FileCheck2: 'task', FileDown: 'download',
  FileImage: 'image', FilePlus: 'note_add', FileSignature: 'signature', FileSpreadsheet: 'table_chart',
  FileText: 'description', FileUp: 'upload_file', FileVideo: 'video_file', Folder: 'folder',
  FolderCog: 'folder_managed', FolderOpen: 'folder_open', Forward: 'forward', Gauge: 'speed',
  GitCompareArrows: 'compare_arrows', Globe: 'public', Grip: 'drag_indicator', HardDrive: 'hard_drive',
  History: 'history', Home: 'home', Hourglass: 'hourglass_empty', Inbox: 'inbox', Info: 'info',
  KanbanSquare: 'view_kanban', KeyRound: 'key', Layers: 'layers', LayoutGrid: 'grid_view', Link: 'link',
  Link2: 'link', Link2Off: 'link_off', ListChecks: 'checklist', ListTree: 'account_tree',
  Loader2: 'progress_activity', LoaderCircle: 'progress_activity', Lock: 'lock', LogOut: 'logout', Mail: 'mail',
  MapPin: 'location_on', Maximize2: 'open_in_full', Menu: 'menu', MessageCircle: 'chat_bubble',
  MessageSquare: 'chat', MessageSquareReply: 'reply', MessagesSquare: 'forum', Minus: 'remove',
  MoreVertical: 'more_vert', Network: 'lan', Paperclip: 'attach_file', PartyPopper: 'celebration',
  PenTool: 'draw', Pencil: 'edit', Play: 'play_arrow', PlayCircle: 'play_circle', Plus: 'add',
  Power: 'power_settings_new', Presentation: 'slideshow', Printer: 'print', Quote: 'format_quote',
  ReceiptText: 'receipt_long', RefreshCw: 'refresh', RotateCcw: 'replay', Save: 'save', Search: 'search',
  SearchX: 'search_off', Send: 'send', Settings2: 'settings', Sheet: 'table_chart', ShieldAlert: 'gpp_maybe',
  ShieldCheck: 'verified_user', SkipForward: 'skip_next', SlidersHorizontal: 'tune', SmilePlus: 'add_reaction',
  Sparkles: 'auto_awesome', Square: 'check_box_outline_blank', SquareCheck: 'check_box',
  SquareKanban: 'view_kanban', SquarePen: 'edit_square', Stamp: 'approval', Tag: 'sell', Target: 'track_changes',
  Text: 'notes', Trash2: 'delete', Undo2: 'undo', Unplug: 'power_off', Upload: 'upload',
  UserCog: 'manage_accounts', UserMinus: 'person_remove', UserPlus: 'person_add', UserRound: 'person',
  UserX: 'person_off', Users: 'group', UsersRound: 'group', Video: 'videocam', X: 'close', XCircle: 'cancel',
  Zap: 'bolt',
};
