const router = require('express').Router();
const rateLimit = require('express-rate-limit');
const { z } = require('zod');
const validate = require('../middleware/validate');
const requireAuth = require('../middleware/requireAuth');
const ctrl = require('../controllers/auth.controller');
const loginLimiter = rateLimit({ windowMs: 60_000, max: 5 });
const schema = z.object({ idToken: z.string().min(10) });
router.post('/google', loginLimiter, validate(schema), ctrl.googleLogin);
router.get('/me', requireAuth, ctrl.me);
module.exports = router;
